# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhmz5L7X_COsOXdSOCHijp5XibLrwtRV
"""

#@title 👨‍⚕️ Testosterone Clinical Dashboard (v4) { display-mode: "form" }

import numpy as np
import matplotlib.pyplot as plt

# --- ส่วนของการกรอกข้อมูล (ตั้งค่า Default ตามคำขอ) ---
Age = 75 #@param {type:"slider", min:18, max:90, step:1}
Test_Value = 3.2 #@param {type:"number"}
Test_Time = "16:00" #@param ["00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30"]

def plot_final_dashboard(age, val, t_str):
    # 1. ข้อมูลอ้างอิงรายทศวรรษ (JCEM 2017 & Brambilla 2009)
    if age < 40:
        m, a = 5.31, 0.75  # วัยหนุ่ม: Mean สูง สวิงชัน
    elif age < 50:
        m, a = 5.05, 0.55
    elif age < 60:
        m, a = 4.85, 0.45  # วัยกลางคน: เริ่มเข้าสู่ภาวะ Blunted Rhythm
    elif age < 70:
        m, a = 4.45, 0.35
    else:
        m, a = 4.00, 0.25  # วัยสูงอายุ: กราฟค่อนข้างราบตลอดวัน

    # 2. สร้างเส้นกราฟ 24 ชม. (Peak 08:00 AM)
    hours = np.linspace(0, 24, 250)
    curve = m + a * np.cos((hours - 8) * (2 * np.pi / 24))

    # 3. คำนวณเวลาคนไข้
    hh, mm = map(int, t_str.split(':'))
    ph = hh + (mm / 60)

    # 4. วาดกราฟ
    plt.figure(figsize=(12, 6), facecolor='#f8f9fa')

    # พื้นที่ Normal Range (95% CI)
    plt.fill_between(hours, curve-1.8, curve+2.5, color='#3498db', alpha=0.1, label='Healthy Reference Range')

    # เส้นค่าเฉลี่ยประชากร
    plt.plot(hours, curve, color='#2c3e50', linewidth=2.5, label=f'Average Curve (Age {age})')

    # เส้นขีดจำกัดล่าง (Critical Threshold 2.1 ng/mL)
    plt.axhline(2.1, color='#e74c3c', linestyle='--', linewidth=2, label='Lower Limit (2.1 ng/mL)')

    # จุดผลตรวจคนไข้
    plt.scatter(ph, val, color='red', s=200, edgecolor='black', zorder=5)
    plt.annotate(f' Result: {val} ng/mL\n Time: {t_str}', (ph, val),
                 xytext=(15, 15), textcoords='offset points', fontweight='bold',
                 bbox=dict(boxstyle='round,pad=0.5', fc='white', alpha=0.9, ec='#2c3e50'))

    # ตกแต่งกราฟ
    plt.title(f'Testosterone Circadian Analysis Dashboard (Patient Age: {age})', fontsize=16, pad=20)
    plt.xlabel('Time of Day (24-Hour Scale)', fontsize=12)
    plt.ylabel('Total Testosterone (ng/mL)', fontsize=12)
    plt.xticks(np.arange(0, 25, 2))
    plt.yticks(np.arange(0, 11, 1))
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.legend(loc='upper right', frameon=True, shadow=True)
    plt.ylim(0, 10.5)

    # ไฮไลต์โซนต่ำกว่าเกณฑ์
    plt.fill_between(hours, 0, 2.1, color='#e74c3c', alpha=0.08)
    plt.text(0.5, 0.5, 'Critical Low Zone (< 2.1 ng/mL)', color='#c0392b', fontweight='bold')

    plt.tight_layout()
    plt.show()

    # --- ส่วนแปลผลภาษาไทย ---
    print("\n" + "="*60)
    print(f"📊 สรุปผลสำหรับคนไข้ (อายุ {age} ปี)")
    print(f"📍 ค่าที่ตรวจได้: {val} ng/mL | เวลาที่เจาะ: {t_str} น.")

    if val == 0:
        print("⚠️ กรุณากรอกระดับฮอร์โมนเพื่อเริ่มการวิเคราะห์")
    elif val < 2.1:
        print("❌ สถานะ: ต่ำกว่าเกณฑ์มาตรฐานทางสถิติ (ต่ำกว่า 2.5th Percentile)")
        print("💡 แนะนำ: ตรวจซ้ำในช่วงเช้า (07:00-09:00) และประเมินอาการทางคลินิกอย่างละเอียด")
    elif val < 3.0:
        print("⚠️ สถานะ: ค่อนข้างต่ำ (Borderline)")
        print("💡 แนะนำ: ปรับพฤติกรรม (การนอน/การออกกำลังกาย) และติดตามผล")
    else:
        print("✅ สถานะ: อยู่ในเกณฑ์ปกติสมวัย")

    # คำนวณค่าคาดการณ์ตอนเช้า (Reverse Projection)
    if val > 0:
        expected_at_time = m + a * np.cos((ph - 8) * (2 * np.pi / 24))
        morning_peak_est = (val / expected_at_time) * (m + a)
        print(f"🕒 ค่าคาดการณ์ที่จุดสูงสุด (08:00 น.): ประมาณ {morning_peak_est:.2f} ng/mL")
    print("="*60)

# รันฟังก์ชัน
plot_final_dashboard(Age, Test_Value, Test_Time)